//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliqtestsandattribute
    {
        public long id { get; set; }
        public long test_id { get; set; }
        public string test_name { get; set; }
        public long department_id { get; set; }
        public long att_id { get; set; }
        public string att_name { get; set; }
    }
}
